steps:
- name: 'gcr.io/cloud-builders/npm:node-10.19.0'
  args: ['ci']
- name: 'gcr.io/cloud-builders/npm:node-10.19.0'
  args: ['run', 'lint']
- name: 'gcr.io/cloud-builders/npm:node-10.19.0'
  args: ['test']
timeout: "1600s"
